version: '3.4'

services:
  flygetter:
    image: ${DOCKER_REGISTRY-}flygetter
    restart: always
    build:
      context: .      
      dockerfile: Dockerfile
    ports:
      - '19121:19121'  #自定义端口
    depends_on:
      - 'docker.mysql'  #表示依赖docker.mysql这个镜像，会在这个镜像构建成功之后才执行
    networks:
      - net-core
  docker.mysql:
    image: mysql:5.7
    restart: always
    command: 
      - default-authentication-plugin=mysql_native_password #这行代码解决无法访问的问题
    volumes: 
      - /data/mysql/data/:/var/lib/mysql/                            #映射mysql的数据目录到宿主机，保存数据 
      - /data/mysql/conf/mysqld.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf   #把mysql的配置文件映射到容器的相应目录
    ports:
      - '3306:3310'
    environment:
      - "MYSQL_ROOT_PASSWORD=12345@MySql"
      - LANG=C.UTF-8
      - TZ=Asia/shanghai
    networks:
      - net-core

networks:
  net-core:
    driver: bridge