version: '3.4'

services:
  flygetter:
    image: ${DOCKER_REGISTRY-}flygetter
    build:
      context: .
      container_name: 'flygetter-server' 
      dockerfile: FlyGetter/Dockerfile
      ports:
        - '19121:19121'  #自定义端口
      depends_on:
        - 'database'  #表示依赖database这个镜像，会在这个镜像构建成功之后才执行
  database:
    image: mysql:5.7
    ports:
      - '3307:3307'
    environment:
      - "MYSQL_ROOT_PASSWORD=root"
      - "MYSQL_DATABASE=larabbs"
      - "MYSQL_USER=homestead"
      - "MYSQL_PASSWORD=secret"
