version: '3.4'

services:
  flygetter:
    image: ${DOCKER_REGISTRY-}flygetter
    restart: always
    build:
      context: .      
      dockerfile: Dockerfile
    ports:
      - '19121:19121'  #自定义端口
    depends_on:
      - 'docker.mysql'  #表示依赖docker.mysql这个镜像，会在这个镜像构建成功之后才执行
    networks:
      - net-core
  docker.mysql:
    image: mysql:5.7
    restart: always
    ports:
      - '3306:3310'
    environment:
      - "MYSQL_ROOT_PASSWORD=123456"
    networks:
      - net-core

networks:
  net-core:
    driver: bridge